name: Cypress Tests December 2023

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: "slawekradzyminski/awesome-localstack"
          path: "awesome-localstack"

      - name: Run Docker Compose
        run: |
          cd awesome-localstack
          chmod +x run-docker-compose.sh
          ./run-docker-compose.sh

      - name: Install
        run: npm install

      - name: Setup Chrome 
        uses: browser-actions/setup-chrome@v1

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
