name: Cypress Tests

on:
  push:
    branches-ignore:    
      - 'develop'

jobs:
  run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: npm install

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          command-prefix: 'percy exec -- npx'
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/isolation/*
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}