name: Node.js CI

on:
  push:
    branches:
      - march2024
      - march2024b

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     browser: [chrome, firefox, edge]
    container:
      image: cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t frontend:latest .
      - name: Run Docker Container
        run: docker run -d -p 8081:8081 frontend:latest
      - name: Cypress run
        run: npx cypress run --browser chrome --spec "cypress/e2e/isolation/*"
